name: Release Workflow

on:
  workflow_dispatch:
    inputs:
      version:
        description: '版本号'
        required: true
        default: '1.0.0'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      # 先创建标签（但暂不推送）
      - name: Create Local Git Tag
        run: |
          TAG_NAME="v${{ github.event.inputs.version }}"
          git tag $TAG_NAME

      # 生成CHANGELOG（此时能识别新标签）
      - name: Generate CHANGELOG
        uses: BobAnkh/auto-generate-changelog@v1.2.5
        with:
          REPO_NAME: ${{ github.repository }}
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATH: 'CHANGELOG.md'
          COMMIT_MESSAGE: 'docs(CHANGELOG): update release notes'
          TYPE: 'feat:新增功能或特性,fix:修复,refactor:重构,perf:优化'
          UNRELEASED_COMMITS: false

      # 推送包含标签的提交
      - name: Push Changes with Tag
        run: |
          git add CHANGELOG.md
          git commit -m "docs: 更新版本日志"
          git push origin main
          git push origin "v${{ github.event.inputs.version }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2.0.8
        with:
          tag_name: "v${{ github.event.inputs.version }}"
          name: "Release v${{ github.event.inputs.version }}"
          body_path: CHANGELOG.md
          files: dist/*